In [10]:
#Â loading necessary packages
import numpy as np
import pandas as pd
import datetime
import random
from faker import Faker

In [4]:
# generating faker object with english settings
fake=Faker('en_US')

# Person (Superclass)

In [7]:
# creates an array of dictionaries, where each dict is a row in DB
# 100 rows by default with id = 1..num_rows

def create_persons(num_rows=100):
    persons = []
    for i in range(num_rows):
        person = {
            'person_id': i+1,
            'p_name': fake.name(),
            'p_phone_number': fake.phone_number(),
            'p_address': fake.address()
        }
        persons.append(person)
        
    return persons

In [11]:
# Testing it out
pd.DataFrame(create_persons())

,person_id,p_name,p_phone_number,p_address
0,1,Megan Hunt,152.827.1325x6353,"99082 David Forges Apt. 063\nWest Danielstad, ..."
1,2,Stephen James,666-273-4093,"181 Green Mall Apt. 726\nMatthewmouth, NE 56820"
2,3,Robert Simmons,478.573.9812,"65220 Andrew Turnpike\nAmandaberg, ME 81927"
3,4,Patricia Powell,001-600-082-9838x0755,"034 Christina Motorway\nEast Sara, OR 91672"
4,5,Michael Williams,001-245-811-0891x2189,"1791 Herrera Road Suite 747\nEast Andreabury, ..."
5,6,Corey Crosby,707.710.1000x46513,"13743 Barbara Haven Suite 630\nPort Johnberg, ..."
6,7,Shannon Martinez,001-402-904-0554,"2990 Kyle Station\nLake Joseph, NC 95367"
7,8,Kelsey Miller,692-244-6991x3517,"5757 Scott Crescent\nWest Johnburgh, LA 67654"
8,9,Christopher Reyes,(904)791-0120,"5713 Salas Rapids Suite 537\nAngelaton, MO 19001"
9,10,Harry Elliott,171-449-6811x314,"212 Krueger River Apt. 875\nNew Juliaborough, ..."
10,11,Charles Leon,+1-103-952-1192x026,"476 Heather Common Apt. 395\nGuerrerotown, TN ..."
11,12,Katherine Gross,297-632-4730x2558,"569 Frank Ferry\nWest Jonathan, RI 05348"
12,13,Clinton Thomas,406.678.7986x823,"06015 Bennett Mountains\nHayeschester, OH 24148"
13,14,Paul Oconnell,776-647-6849,"978 Jamie Neck Apt. 001\nRandymouth, ID 80412"
14,15,Don Robinson,9309128535,"020 Dana Unions Suite 505\nNorth Ryanburgh, TN..."
15,16,Cathy Atkinson,953.740.4488x64888,"499 Anthony Viaduct\nSanfordburgh, SC 30718"
16,17,Corey Calhoun,4784768671,"50971 Doyle Ferry\nEast Kimberlyburgh, PA 85308"
17,18,Pamela Davidson,(496)512-3320x23053,"624 Lisa Stravenue Apt. 849\nPort Wendymouth, ..."
18,19,Douglas Cabrera,+1-585-845-9277,"81786 Hicks Mission\nWest Michealport, WA 14378"
19,20,John Kim Jr.,924-468-9101x080,"8402 Taylor Land Suite 474\nPattersonchester, ..."
20,21,Daniel Ortiz,+1-258-408-4472x66241,"715 Byrd Lodge Apt. 012\nWest Ricardo, FL 24931"
21,22,Lisa Rogers PhD,(594)783-1597,"52604 Guzman Shoals\nKatherinefort, NC 14585"
22,23,Robin Jenkins,+1-056-581-6506x88782,"3093 Shannon Valleys\nMillerhaven, ND 45962"
23,24,James Phillips,815.827.8800x2321,"33543 Davis Tunnel\nWest Jacobland, DE 90965"
24,25,Alexis Hart,722.650.0500x6089,"43764 Katie Coves\nWest Michellefort, IL 67819"
25,26,Tiffany Miles,(364)024-1160x51059,94668 Curtis Key Apt. 219\nNorth Margaretshire...
26,27,Aaron Parker,788.850.7520,40278 Pace Station Suite 428\nNorth Cassiehave...
27,28,Monica Wade,238.501.5669x50029,"2159 Robert Station Apt. 111\nAnthonyberg, CT ..."
28,29,Jonathan Thompson,(749)349-7716,"622 Phillip Parkway Suite 498\nEast Nicole, OH..."
29,30,Charles Schmidt,369.388.5648x463,"88631 Arthur Trail\nMarshallbury, IN 40859"
30,31,Allen Nguyen,050-787-1215x0770,"211 Michele Lake Apt. 219\nCodyfort, CO 46320"
31,32,Tara Giles,242-890-2137x300,"63404 Evans Orchard Apt. 125\nPort Mariah, NM ..."
32,33,Helen Haynes,(561)684-4969x57146,"04500 Lee Mills\nBrownchester, NJ 87426"
33,34,Eric Bryant,+1-029-759-9693x37871,USNV Davis\nFPO AP 69910
34,35,Dawn Lindsey,+1-908-962-8509,"8688 Lewis Heights Apt. 070\nDavisstad, NY 62879"
35,36,Kyle Lara,+1-703-614-1367,"80702 Berg Ways\nWest James, AL 10663"
36,37,Andrew Cole,285.745.2383,"148 Rice Prairie Suite 081\nBrentmouth, OK 45213"
37,38,Charlene Chandler,001-334-358-4805,"28971 Montoya Cliff Apt. 985\nMichaelfurt, AL ..."
38,39,Andrea Myers,919.500.5546,"9768 Rachel Plaza Apt. 798\nSheilahaven, NV 15617"
39,40,Alexandra Turner,(886)773-1599,"16045 Matthew Parkway Suite 951\nNew John, AR ..."
40,41,Lauren Collins,(362)479-5807x2168,"PSC 5889, Box 5215\nAPO AE 62333"
41,42,Steven Brown,001-578-459-5177x385,"07001 Brooke Island\nLorihaven, WA 43473"
42,43,Anthony Adams,+1-173-412-9079x5342,"0392 Petty Isle\nClarkchester, GA 70038"
43,44,Jon Hernandez,402.608.9499,"4729 Drake Walk\nSmithshire, IN 66025"
44,45,David Jackson,001-789-746-5679x891,7784 Jessica Motorway Apt. 693\nNew Jonathanha...
45,46,Kevin Smith,636-666-9889,"46203 Kenneth Canyon Apt. 844\nFergusonmouth, ..."
46,47,Allison Rollins,001-159-130-0823x5862,"1424 Amanda Circle\nPort Johnchester, PA 14567"
47,48,Aimee Meza,629.214.9058x60419,"780 Jeffrey Glens\nStephaniestad, AZ 80033"
48,49,Christopher Reeves,492-394-2726x5231,"PSC 5962, Box 1444\nAPO AP 37107"
49,50,Catherine Barker,800-228-3605,"3192 Sharp Hill\nLake Joshuaton, AL 08970"

# Person Subclasses (surf_teacher, surfer, event_staff, other_person)

In [18]:
# the first 10 persons of the db are surf teachers
def create_surf_teachers(num_rows=10):
    surf_teachers = []
    for i in range(num_rows):
        surf_teacher = {
                # assign id 1..10 to the teachers
                'person_id': i+1,
                'hourly_rate': random.randint(15, 50)
            }
        surf_teachers.append(surf_teacher)
        
    return surf_teachers

In [19]:
# testing
create_surf_teachers()

[{'person_id': 1, 'hourly_rate': 38},
 {'person_id': 2, 'hourly_rate': 42},
 {'person_id': 3, 'hourly_rate': 37},
 {'person_id': 4, 'hourly_rate': 49},
 {'person_id': 5, 'hourly_rate': 36},
 {'person_id': 6, 'hourly_rate': 17},
 {'person_id': 7, 'hourly_rate': 43},
 {'person_id': 8, 'hourly_rate': 20},
 {'person_id': 9, 'hourly_rate': 31},
 {'person_id': 10, 'hourly_rate': 40}]

In [31]:
# the next 40 persons (id 11...50) of the db are surfers
def create_surfers(num_rows=40):
    surfers = []
    for i in range(num_rows):
        surfer = {
                'person_id': 10+(i+1),
            }
        surfers.append(surfer)
        
    return surfers

In [32]:
# testing
create_surfers()

[{'person_id': 11},
 {'person_id': 12},
 {'person_id': 13},
 {'person_id': 14},
 {'person_id': 15},
 {'person_id': 16},
 {'person_id': 17},
 {'person_id': 18},
 {'person_id': 19},
 {'person_id': 20},
 {'person_id': 21},
 {'person_id': 22},
 {'person_id': 23},
 {'person_id': 24},
 {'person_id': 25},
 {'person_id': 26},
 {'person_id': 27},
 {'person_id': 28},
 {'person_id': 29},
 {'person_id': 30},
 {'person_id': 31},
 {'person_id': 32},
 {'person_id': 33},
 {'person_id': 34},
 {'person_id': 35},
 {'person_id': 36},
 {'person_id': 37},
 {'person_id': 38},
 {'person_id': 39},
 {'person_id': 40},
 {'person_id': 41},
 {'person_id': 42},
 {'person_id': 43},
 {'person_id': 44},
 {'person_id': 45},
 {'person_id': 46},
 {'person_id': 47},
 {'person_id': 48},
 {'person_id': 49},
 {'person_id': 50}]

In [28]:
# the next 10 persons (id 51...60) of the db are event staff
def create_event_staffers(num_rows=10):
    event_staffers = []
    ### TODO: insert here any role that an event staff can have
    roles = ['security', 'catering', 'organization', 'other' ]
    for i in range(num_rows):
        event_staffer = {
                'person_id': 50+(i+1),
                'role': random.sample(roles, 1)[0],
            }
        event_staffers.append(event_staffer)
        
    return event_staffers

In [29]:
# testing
create_event_staffers()

[{'person_id': 51, 'role': 'catering'},
 {'person_id': 52, 'role': 'security'},
 {'person_id': 53, 'role': 'security'},
 {'person_id': 54, 'role': 'catering'},
 {'person_id': 55, 'role': 'catering'},
 {'person_id': 56, 'role': 'catering'},
 {'person_id': 57, 'role': 'other'},
 {'person_id': 58, 'role': 'catering'},
 {'person_id': 59, 'role': 'catering'},
 {'person_id': 60, 'role': 'organization'}]

In [33]:
# the last 40 persons (id 61...100) of the db are 'others'
def create_other_persons(num_rows=40):
    other_persons = []
    ### TODO: insert here any type that an other_person can have
    types = ['customer', 'store_staff', 'marketing_lead']
    for i in range(num_rows):
        other_person = {
                'person_id': 60+(i+1),
                'role': random.sample(types, 1)[0],
            }
        other_persons.append(other_person)
        
    return other_persons

In [34]:
create_other_persons()

[{'person_id': 61, 'role': 'marketing_lead'},
 {'person_id': 62, 'role': 'store_staff'},
 {'person_id': 63, 'role': 'marketing_lead'},
 {'person_id': 64, 'role': 'marketing_lead'},
 {'person_id': 65, 'role': 'store_staff'},
 {'person_id': 66, 'role': 'marketing_lead'},
 {'person_id': 67, 'role': 'customer'},
 {'person_id': 68, 'role': 'marketing_lead'},
 {'person_id': 69, 'role': 'marketing_lead'},
 {'person_id': 70, 'role': 'marketing_lead'},
 {'person_id': 71, 'role': 'customer'},
 {'person_id': 72, 'role': 'customer'},
 {'person_id': 73, 'role': 'store_staff'},
 {'person_id': 74, 'role': 'store_staff'},
 {'person_id': 75, 'role': 'marketing_lead'},
 {'person_id': 76, 'role': 'marketing_lead'},
 {'person_id': 77, 'role': 'customer'},
 {'person_id': 78, 'role': 'marketing_lead'},
 {'person_id': 79, 'role': 'store_staff'},
 {'person_id': 80, 'role': 'store_staff'},
 {'person_id': 81, 'role': 'store_staff'},
 {'person_id': 82, 'role': 'customer'},
 {'person_id': 83, 'role': 'customer'},
 {'person_id': 84, 'role': 'marketing_lead'},
 {'person_id': 85, 'role': 'customer'},
 {'person_id': 86, 'role': 'marketing_lead'},
 {'person_id': 87, 'role': 'store_staff'},
 {'person_id': 88, 'role': 'customer'},
 {'person_id': 89, 'role': 'customer'},
 {'person_id': 90, 'role': 'store_staff'},
 {'person_id': 91, 'role': 'marketing_lead'},
 {'person_id': 92, 'role': 'customer'},
 {'person_id': 93, 'role': 'store_staff'},
 {'person_id': 94, 'role': 'marketing_lead'},
 {'person_id': 95, 'role': 'customer'},
 {'person_id': 96, 'role': 'store_staff'},
 {'person_id': 97, 'role': 'store_staff'},
 {'person_id': 98, 'role': 'customer'},
 {'person_id': 99, 'role': 'customer'},
 {'person_id': 100, 'role': 'marketing_lead'}]

#Â Item (Superclass) + its subclasses

In [51]:
# creates 50 items total.
# First 5 will be paddles, Next 10 gear, next 20 boards, next 5 wetsuit, last 10 other item
def create_items(num_rows=50):
    items = []
    ### TODO: add any surfbrands
    brands = ['Quiksilver', 'Ripcurl', 'Billabong', "O'Neill", 'Volcom', 'Vans', 'Hurley']
    for i in range(num_rows):
        if i < 5:
            item_name = f"Paddle#{i+1}"
        elif i < 15:
            item_name = f"Gear#{i+1-5}"
        elif i < 35:
            item_name = f"Board#{i+1-15}"
        elif i < 40:
            item_name = f"Wetsuit#{i+1-35}"
        else:
            item_name = f"Other#{i+1-40}"
        
        item = {
            'item_id': i+1,
            'i_name': item_name,
            'brand': random.sample(brands, 1)[0],
            'description': fake.paragraph(nb_sentences=3)
        }
        items.append(item)
        
    return items

def create_paddles(num_rows=5):
    elements = []
    ### TODO: insert here any type that an other_person can have
    materials = ['Carbon Fiber', 'Metal', 'Plastic', 'Silicon']
    ### TODO: are paddle sizes in meters or in SMLXL?
    sizes = ['XS', 'S', 'M', 'L', 'XL']
    for i in range(num_rows):
        element = {
                'itenm_id': (i+1),
                'material': random.sample(materials, 1)[0],
                # assuming kilograms for weight
                'weight': random.randint(1, 8),
                'size': random.sample(sizes, 1)[0],
            }
        elements.append(element)
        
    return element

def create_gears(num_rows=10):
    elements = []
    ### TODO: add any categories
    categories = ['Accessories', 'Clothing', 'Surf Supplements', 'Miscellaneous']
    sizes = ['XS', 'S', 'M', 'L', 'XL']
    genders = ['M', 'F', 'Unisex']
    for i in range(num_rows):
        element = {
                'item_id': 5+(i+1),
                'category': random.sample(categories, 1)[0],
                'gender': random.sample(genders, 1)[0],
                'size': random.sample(sizes, 1)[0],
            }
        elements.append(element)
        
    return elements

def create_surfboards(num_rows=20):
    elements = []
    ### TODO: @surfers - Please fill with things that make sense
    shapes = ['shape1', 'shape2', 'shape3']
    materials = ['Carbon Fiber', 'Plastic', 'Silicon']
    levels = [1, 2, 3, 4, 5, 6]
    
    for i in range(num_rows):
        element = {
                'item_id': 15+(i+1),
                'shape': random.sample(categories, 1)[0],
                'gender': random.sample(genders, 1)[0],
                'size': random.sample(sizes, 1)[0],
            }
        elements.append(element)
        
    return elements

def create_wetsuits(num_rows=5):
    elements = []
    sizes = ['XS', 'S', 'M', 'L', 'XL']
    genders = ['M', 'F', 'Unisex']
    
    for i in range(num_rows):
        element = {
                'item_id': 35+(i+1),
                #Â assuming thickness in mm ranges from 0.1 to 0.9
                'thickness': random.randint(1, 9)/10,
                'gender': random.sample(genders, 1)[0],
                'size': random.sample(sizes, 1)[0],
            }
        elements.append(element)
        
    return elements

def create_other_items(num_rows=5):
    elements = []
    sizes = ['XS', 'S', 'M', 'L', 'XL']
    genders = ['M', 'F', 'Unisex']
    
    for i in range(num_rows):
        element = {
                'item_id': 35+(i+1),
                #Â assuming thickness in mm ranges from 0.1 to 0.9
                'thickness': random.randint(1, 9)/10,
                'gender': random.sample(genders, 1)[0],
                'size': random.sample(sizes, 1)[0],
            }
        elements.append(element)
        
    return elements


def create_other_items(num_rows=10):
    elements = []
    
    for i in range(num_rows):
        element = {
                'item_id': 40+(i+1)
            }
        elements.append(element)
        
    return elements

In [52]:
# testing
create_other_items()

[{'item_id': 41},
 {'item_id': 42},
 {'item_id': 43},
 {'item_id': 44},
 {'item_id': 45},
 {'item_id': 46},
 {'item_id': 47},
 {'item_id': 48},
 {'item_id': 49},
 {'item_id': 50}]

#Â Shop

In [70]:
# creating 20 surf shops
def create_shops(num_rows=20):
    elements = []
    opening_times = ['7:00', '7:30', '8:00', '8:30', '9:00']
    closing_times = ['16:30', '17:00', '17:30', '18:00', '18:30']
    for i in range(num_rows):
        element = {
                # assign id 1..10 to the teachers
                'shop_id': i+1,
                's_name': f"{fake.city()} Surf Shop",
                's_address': fake.address(),
                's_phone_number': fake.phone_number(),
                'opening_time': random.sample(opening_times, 1)[0],
                'closing_time': random.sample(closing_times, 1)[0]
            }
        elements.append(element)
        
    return elements

In [71]:
# testing
create_shops()

[{'shop_id': 1,
  's_name': 'New Saraport Surf Shop',
  's_address': '6158 Renee Meadows Apt. 330\nSouth Sergio, VT 38190',
  's_phone_number': '(141)735-8039x57362',
  'opening_time': '7:30',
  'closing_time': '18:30'},
 {'shop_id': 2,
  's_name': 'Brandyville Surf Shop',
  's_address': '588 Harrington Forest\nLake Crystalfort, MS 50674',
  's_phone_number': '244.925.4622x87474',
  'opening_time': '7:00',
  'closing_time': '18:00'},
 {'shop_id': 3,
  's_name': 'Lake Richardton Surf Shop',
  's_address': '9304 Samuel Loaf Suite 767\nYoungburgh, MN 21352',
  's_phone_number': '8161115642',
  'opening_time': '7:00',
  'closing_time': '17:30'},
 {'shop_id': 4,
  's_name': 'Susanview Surf Shop',
  's_address': '0506 David Prairie Apt. 864\nLopezfort, CA 34080',
  's_phone_number': '233-074-0473x19573',
  'opening_time': '8:30',
  'closing_time': '16:30'},
 {'shop_id': 5,
  's_name': 'Nicholasshire Surf Shop',
  's_address': '6114 David Park\nGilbertmouth, WV 80251',
  's_phone_number': '(414)268-5278x1110',
  'opening_time': '9:00',
  'closing_time': '18:30'},
 {'shop_id': 6,
  's_name': 'Smithstad Surf Shop',
  's_address': 'PSC 1834, Box 6530\nAPO AA 30192',
  's_phone_number': '429.312.6789',
  'opening_time': '8:30',
  'closing_time': '16:30'},
 {'shop_id': 7,
  's_name': 'Jamiefort Surf Shop',
  's_address': '4220 Luke Street\nDavishaven, ND 67761',
  's_phone_number': '713.516.8527',
  'opening_time': '9:00',
  'closing_time': '18:30'},
 {'shop_id': 8,
  's_name': 'Lake Allisonbury Surf Shop',
  's_address': '13367 Johnson Via\nDoughertyville, WY 39803',
  's_phone_number': '001-106-435-9143x72640',
  'opening_time': '8:30',
  'closing_time': '16:30'},
 {'shop_id': 9,
  's_name': 'Jamesport Surf Shop',
  's_address': '50504 Simmons Spur Suite 292\nSchultzmouth, AZ 16761',
  's_phone_number': '001-896-078-4657x68318',
  'opening_time': '8:30',
  'closing_time': '16:30'},
 {'shop_id': 10,
  's_name': 'West Michaelside Surf Shop',
  's_address': '935 Park Glen\nDonaldburgh, ME 59344',
  's_phone_number': '001-896-527-9500x813',
  'opening_time': '7:30',
  'closing_time': '17:00'},
 {'shop_id': 11,
  's_name': 'Ericside Surf Shop',
  's_address': '6657 Anthony Alley\nSamanthafurt, MA 25929',
  's_phone_number': '001-549-147-2436x091',
  'opening_time': '7:30',
  'closing_time': '18:00'},
 {'shop_id': 12,
  's_name': 'Joshuaton Surf Shop',
  's_address': '49351 Jennifer Fords\nStephaniemouth, NH 11093',
  's_phone_number': '704-912-6854',
  'opening_time': '7:30',
  'closing_time': '17:30'},
 {'shop_id': 13,
  's_name': 'Port Justinberg Surf Shop',
  's_address': '076 Brooke Pine\nPort Daniel, OH 43528',
  's_phone_number': '(749)949-6753x06420',
  'opening_time': '7:00',
  'closing_time': '18:00'},
 {'shop_id': 14,
  's_name': 'Port Albertstad Surf Shop',
  's_address': '298 Peters Squares Suite 456\nNicholston, WA 54589',
  's_phone_number': '(596)643-0213',
  'opening_time': '7:30',
  'closing_time': '17:00'},
 {'shop_id': 15,
  's_name': 'Amyton Surf Shop',
  's_address': '52769 Kendra Keys\nTonyaland, RI 38916',
  's_phone_number': '870-917-8215',
  'opening_time': '7:00',
  'closing_time': '17:30'},
 {'shop_id': 16,
  's_name': 'Hollandshire Surf Shop',
  's_address': '5365 Jesse Mission\nDawnland, HI 07004',
  's_phone_number': '941-376-2591x107',
  'opening_time': '7:00',
  'closing_time': '18:30'},
 {'shop_id': 17,
  's_name': 'Moorefurt Surf Shop',
  's_address': '25751 Kathryn Plains\nClarkfort, SD 41302',
  's_phone_number': '+1-498-553-1359x4905',
  'opening_time': '7:00',
  'closing_time': '17:30'},
 {'shop_id': 18,
  's_name': 'Jamesview Surf Shop',
  's_address': '6946 Jamie Extension Suite 345\nEast Alexanderborough, AL 53738',
  's_phone_number': '+1-280-636-7546',
  'opening_time': '8:00',
  'closing_time': '17:00'},
 {'shop_id': 19,
  's_name': 'Lake Jessicaborough Surf Shop',
  's_address': '11055 Randall Plain Apt. 842\nLake Rebecca, KS 60639',
  's_phone_number': '+1-963-927-6477x25026',
  'opening_time': '9:00',
  'closing_time': '17:30'},
 {'shop_id': 20,
  's_name': 'Kimbury Surf Shop',
  's_address': '65480 Allen Via\nKennethfurt, NC 17694',
  's_phone_number': '(784)987-8286x450',
  'opening_time': '7:30',
  'closing_time': '17:30'}]

In [72]:
# creating 7 manufacturers
def create_manufacturers(num_rows=7):
    elements = []
    brands = ['Quiksilver', 'Ripcurl', 'Billabong', "O'Neill", 'Volcom', 'Vans', 'Hurley']
    for i, brand in enumerate(brands):
        element = {
                # assign id 1..10 to the teachers
                'manufacturer_id': i+1,
                'm_name': brand
            }
        elements.append(element)
        
    return elements

In [73]:
# creating 20 surf shops
def create_shops(num_rows=20):
    elements = []
    opening_times = ['7:00', '7:30', '8:00', '8:30', '9:00']
    closing_times = ['16:30', '17:00', '17:30', '18:00', '18:30']
    for i in range(num_rows):
        element = {
                # assign id 1..10 to the teachers
                'shop_id': i+1,
                's_name': f"{fake.city()} Surf Shop",
                's_address': fake.address(),
                's_phone_number': fake.phone_number(),
                'opening_time': random.sample(opening_times, 1)[0],
                'closing_time': random.sample(closing_times, 1)[0]
            }
        elements.append(element)
        
    return elements

[{'manufacturer_id': 1, 'm_name': 'Quiksilver'},
 {'manufacturer_id': 2, 'm_name': 'Ripcurl'},
 {'manufacturer_id': 3, 'm_name': 'Billabong'},
 {'manufacturer_id': 4, 'm_name': "O'Neill"},
 {'manufacturer_id': 5, 'm_name': 'Volcom'},
 {'manufacturer_id': 6, 'm_name': 'Vans'},
 {'manufacturer_id': 7, 'm_name': 'Hurley'}]